lib/learn_u_web/router.ex
defmodule LearnUWeb.Router do
  use LearnUWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", LearnUWeb do
    pipe_through :browser # Use the default browser stack

    get "/", PageController, :index

    get "/register", Accounts.RegistrationController, :new
    post "/register", Accounts.RegistrationController, :create

    get "/login", SessionController, :new
    post "/login", SessionController, :create

    delete "/logout", SessionController, :delete

    resources "/accounts/password", Accounts.PasswordController,
      only: [:new, :create, :edit, :update],
      singleton: true
  end

  # Other scopes may use custom stacks.
  # scope "/api", LearnUWeb do
  #   pipe_through :api
  # end
end

lib/learn_u/application.ex
defmodule LearnU.Application do
  use Application

  # See https://hexdocs.pm/elixir/Application.html
  # for more information on OTP Applications
  def start(_type, _args) do
    import Supervisor.Spec

    # Define workers and child supervisors to be supervised
    children = [
      # Start the Ecto repository
      supervisor(LearnU.Repo, []),
      # Start the endpoint when the application starts
      supervisor(LearnUWeb.Endpoint, []),
      # Start your own worker by calling: LearnU.Worker.start_link(arg1, arg2, arg3)
      # worker(LearnU.Worker, [arg1, arg2, arg3]),
    ]

    # See https://hexdocs.pm/elixir/Supervisor.html
    # for other strategies and supported options
    opts = [strategy: :one_for_one, name: LearnU.Supervisor]
    Supervisor.start_link(children, opts)
  end

  # Tell Phoenix to update the endpoint configuration
  # whenever the application is updated.
  def config_change(changed, _new, removed) do
    LearnUWeb.Endpoint.config_change(changed, removed)
    :ok
  end
end

lib/learn_u/repo.ex
defmodule LearnU.Repo do
  use Ecto.Repo, otp_app: :learn_u

  @doc """
  Dynamically loads the repository url from the
  DATABASE_URL environment variable.
  """
  def init(_, opts) do
    {:ok, Keyword.put(opts, :url, System.get_env("DATABASE_URL"))}
  end
end

lib/learn_u_web/controllers/accounts/password_controller.ex
defmodule LearnUWeb.Accounts.PasswordController do
  use LearnUWeb, :controller

  plug :scrub_params, "account" when action in [:create, :update]

  def new(conn, _params) do
    render(conn, "new.html")
  end

  def create(conn, %{"account" => %{"email" => email}}) do
    # Send instructions via email
    conn
    |> put_flash(:info, "You will receive password reset instructions momentarily.")
    |> render("new.html")
  end

  def edit(conn, %{"t" => token}) do
    render(conn, "edit.html")
  end

  def update(conn, %{"account" => params}) do
    # Update the account password. Handle success and failure.
    conn
    |> put_flash(:info, "Password successfully reset. Please try logging in again.")
    |> redirect(to: session_path(conn, :new))
  end
end

lib/learn_u_web/controllers/accounts/registration_controller.ex
defmodule LearnUWeb.Accounts.RegistrationController do
  use LearnUWeb, :controller

  alias LearnU.Accounts

  plug :scrub_params, "registration" when action in [:create]

  def new(conn, _params) do
    render conn, "new.html"
  end

  def create(conn, %{"registration" => params}) do
    render conn, "new.html"
  end
end

lib/learn_u_web/controllers/page_controller.ex
defmodule LearnUWeb.PageController do
  use LearnUWeb, :controller

  def index(conn, _params) do
    render conn, "index.html"
  end
end

lib/learn_u_web/controllers/session_controller.ex
defmodule LearnUWeb.SessionController do
  use LearnUWeb, :controller

  plug :scrub_params, "session" when action in [:create]

  def new(conn, _params) do
    render(conn, "new.html")
  end

  @spec create(Plug.Conn.t, map) :: Plug.Conn.t
  def create(conn, %{"session" => params}) do
    render(conn, "new.html")
  end

  @spec delete(Plug.Conn.t, map) :: Plug.Conn.t
  def delete(conn, _params) do
    conn
    |> put_flash(:info, "You've been successfully logged out.")
    |> redirect(to: session_path(conn, :new))
  end
end

lib/learn_u_web/views/accounts/password_view.ex
defmodule LearnUWeb.Accounts.PasswordView do
  use LearnUWeb, :view
end

lib/learn_u_web/views/accounts/registration_view.ex
defmodule LearnUWeb.Accounts.RegistrationView do
  use LearnUWeb, :view
end

lib/learn_u_web/views/error_view.ex
defmodule LearnUWeb.ErrorView do
  use LearnUWeb, :view

  # If you want to customize a particular status code
  # for a certain format, you may uncomment below.
  # def render("500.html", _assigns) do
  #   "Internal Server Error"
  # end

  # By default, Phoenix returns the status message from
  # the template name. For example, "404.html" becomes
  # "Not Found".
  def template_not_found(template, _assigns) do
    Phoenix.Controller.status_message_from_template(template)
  end
end

lib/learn_u_web/views/layout_view.ex
defmodule LearnUWeb.LayoutView do
  use LearnUWeb, :view
end

lib/learn_u_web/views/page_view.ex
defmodule LearnUWeb.PageView do
  use LearnUWeb, :view
end

lib/learn_u_web/views/session_view.ex
defmodule LearnUWeb.SessionView do
  use LearnUWeb, :view
end

lib/learn_u_web/templates/accounts/password/edit.html.eex
<%= form_for @conn, password_path(@conn, :update), [as: :account, method: :put], fn f -> %>
  <%= hidden_input f, :password_reset_token %>

  <div class="row m-t-3">
    <div class="col s12 m6 offset-m3">
      <div class="card grey lighten-5">
        <div class="card-content">
          <div class="input-field">
            <%= password_input f, :password, class: "validate", placeholder: "Enter new password" %>
            <%= label f, :password, "Password" %>
          </div>

          <div class="input-field">
            <%= password_input f, :password_confirmation, class: "validate", placeholder: "Confirm new password" %>
            <%= label f, :password_confirmation, "Confirm Password" %>
          </div>
        </div>

        <div class="card-action valign-wrapper">
          <%= submit(class: "btn-large waves-effect waves-light") do %>
            Reset Password
            <i class="material-icons right">chevron_right</i>
          <% end %>
        </div>
      </div>
    </div>
<% end %>

lib/learn_u_web/templates/accounts/password/new.html.eex
<%= form_for @conn, password_path(@conn, :create), [as: :account], fn f -> %>
  <div class="row m-t-3">
    <div class="col s12 m6 offset-m3">
      <div class="card grey lighten-5">
        <div class="card-content">
          <div class="input-field">
            <%= email_input f, :email, class: "validate" %>
            <%= label f, :email, "Email" %>
          </div>
        </div>

        <div class="card-action valign-wrapper">
          <%= submit(class: "btn-large waves-effect waves-light") do %>
            Send Instructions
            <i class="material-icons right">send</i>
          <% end %>
        </div>
      </div>
    </div>
<% end %>

lib/learn_u_web/templates/layout/app.html.eex
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>LearnU</title>

    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <link rel="stylesheet" href="<%= static_path(@conn, "/css/app.css") %>">

    <meta name="viewport" content="width=device-width, initial-scale=1">
  </head>

  <body>
    <nav class="deep-purple darken-4" role="navigation">
      <div class="nav-wrapper container">
        <a href="/" class="brand-logo">
          <i class="material-icons">school</i>
          LearnU
        </a>

        <ul class="right hide-on-med-and-down">
          <li>
            <a href="register" class="waves-effect waves-light btn">Register</a>
          </li>
          <li>
            <%= link "Login", to: session_path(@conn, :new), class: "waves-effect waves-light btn" %>
          </li>
        </ul>

        <ul class="sidenav" id="nav-mobile">
          <li><a href="/register">Register</a></li>
          <li><%= link "Login", to: session_path(@conn, :new) %></li>
        </ul>
        <a href="#" data-target="nav-mobile" class="sidenav-trigger"><i class="material-icons">menu</i></a>
      </div>
    </nav>

    <div class="container">
      <main role="main">
        <%= render @view_module, @view_template, assigns %>
      </main>
    </div>

    <script type="text/javascript" src="<%= static_path(@conn, "/js/app.js") %>"></script>
  </body>
</html>

lib/learn_u_web/templates/page/index.html.eex
<div class="jumbotron">
  <h2><%= gettext "Welcome to %{name}!", name: "Phoenix" %></h2>
  <p class="lead">A productive web framework that<br />does not compromise speed and maintainability.</p>
</div>

<div class="row marketing">
  <div class="col-lg-6">
    <h4>Resources</h4>
    <ul>
      <li>
        <a href="http://phoenixframework.org/docs/overview">Guides</a>
      </li>
      <li>
        <a href="https://hexdocs.pm/phoenix">Docs</a>
      </li>
      <li>
        <a href="https://github.com/phoenixframework/phoenix">Source</a>
      </li>
    </ul>
  </div>

  <div class="col-lg-6">
    <h4>Help</h4>
    <ul>
      <li>
        <a href="http://groups.google.com/group/phoenix-talk">Mailing list</a>
      </li>
      <li>
        <a href="http://webchat.freenode.net/?channels=elixir-lang">#elixir-lang on freenode IRC</a>
      </li>
      <li>
        <a href="https://twitter.com/elixirphoenix">@elixirphoenix</a>
      </li>
    </ul>
  </div>
</div>

lib/learn_u_web/templates/session/new.html.eex
<%= form_for @conn, session_path(@conn, :create), [as: :session], fn f -> %>
  <div class="row m-t-3">
    <div class="col s12 m6 offset-m3">
      <div class="card grey lighten-5">
        <div class="card-content">
          <div class="input-field">
            <%= email_input f, :email, class: "validate" %>
            <%= label f, :email, "Email" %>
          </div>

          <div class="input-field">
            <%= password_input f, :password, class: "validate" %>
            <%= label f, :password, "Password" %>
          </div>
        </div>

        <div class="card-action valign-wrapper">
          <%= submit(class: "btn-large waves-effect waves-light") do %>
            Login
            <i class="material-icons right">chevron_right</i>
          <% end %>

          <div class="m-l-auto">
            <%= link "Forgot your Password?", to: password_path(@conn, :new), class: "deep-purple-text text-darken-4" %>
          </div>
        </div>
      </div>
  </div>
<% end %>